#!/usr/bin/env python3
"""Write the MPC touchscreen page sources (vst.json, params.json, layout.conf) for the four Dragonfly plugins.

    pages.py <params dir> <out dir>

<params dir>/<Plugin>.raw.json is each plugin's own parameter list (tools/vst_test --params-json): the VST index
order, names, units and choice labels come from the plugin itself, so the page binds to the right parameters.
The layout (which knobs go in which section) is below. Text on the page is 1.35x (nam-mpc/skin/text_scale.py), so
knobs are placed with that in mind: a knob of radius r needs r+5 above its centre and r+72 below it.
"""
import json
import os
import re
import sys

# name, vendor exactly as the plugin reports them (the page folder is "<vendor> - VST - <name>"), 4-char uid
PLUGINS = {
    "DragonflyHallReverb": ("Dragonfly Hall Reverb", "Michael Willis and Rob vd Berg", "dfr1"),
    "DragonflyRoomReverb": ("Dragonfly Room Reverb", "Michael Willis", "dfr2"),
    "DragonflyPlateReverb": ("Dragonfly Plate Reverb", "Michael Willis", "dfp3"),
    "DragonflyEarlyReflections": ("Dragonfly Early Reflections", "Michael Willis", "dfer"),
}

# Rows of sections: (title, [parameter names]) per section; a section holding one choice parameter becomes buttons.
LAYOUTS = {
    "DragonflyHallReverb": [
        [("MIX", ["Dry Level", "Early Level", "Late Level", "Early Send"]), ("MOTION", ["Spin", "Wander"])],
        [("SPACE", ["Size", "Width", "Predelay", "Diffuse", "Decay", "Modulation"])],
        [("TONE", ["Low Cut", "Low Cross", "Low Mult", "High Cut", "High Cross", "High Mult"])],
    ],
    "DragonflyRoomReverb": [
        [("MIX", ["Dry Level", "Early Level", "Early Send", "Late Level"]), ("MOTION", ["Spin", "Wander"])],
        [("SPACE", ["Size", "Width", "Predelay", "Decay", "Diffuse"])],
        [("TONE", ["Low Cut", "Low Boost", "Boost Freq", "High Cut", "Early Damp", "Late Damp"])],
    ],
    "DragonflyPlateReverb": [
        [("MIX", ["Dry Level", "Wet Level"]), ("ALGORITHM", ["Algorithm"])],
        [("SPACE", ["Width", "Predelay", "Decay"]), ("TONE", ["Low Cut", "High Cut", "Dampen"])],
    ],
    "DragonflyEarlyReflections": [
        [("MIX", ["Dry Level", "Wet Level"]), ("ROOM", ["Size", "Width"]), ("TONE", ["Low Cut", "High Cut"])],
        [("PROGRAM", ["Program"])],
    ],
}

X0, X1, Y0, GAP = 20, 1260, 96, 6     # page area (Force Shadow canvas), gap between sections
TITLE = 50                             # a section title's height
SLOT = 206                             # width given to one knob


def key(name):
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def main(pdir, out):
    for plug, (name, vendor, uid) in PLUGINS.items():
        raw = json.load(open(os.path.join(pdir, plug + ".raw.json")))
        by_name = {p["name"]: p for p in raw}
        params = []
        for p in raw:   # VST index order
            q = {"key": key(p["name"]), "name": p["name"]}
            if p.get("options"):
                q["options"] = p["options"]
            else:
                q.update({"min": 0, "max": 1, "unit": p["unit"]})
            params.append(q)
        rows = LAYOUTS[plug]
        used = [n for row in rows for _, names in row for n in names]
        missing = sorted(set(by_name) - set(used))
        unknown = sorted(set(used) - set(by_name))
        if missing or unknown:
            sys.exit("%s: layout doesn't match the plugin: missing %s, unknown %s" % (plug, missing, unknown))

        r = 32 if len(rows) >= 3 else 42               # knob radius: smaller when three rows must fit
        row_h = TITLE + (r + 5) + (r + 72) + 8
        lines = ["# %s page: generated by dragonfly-mpc/pages.py" % name, "[tab %s]" % name.split()[1].upper()]
        qlinks = []
        y = Y0
        for row in rows:
            # section widths follow their contents: a knob takes SLOT, a choice section takes what's left over
            slots = [len(names) if not by_name[names[0]].get("options") else None for _, names in row]
            nchoice = sum(1 for s in slots if s is None)
            slot = SLOT if nchoice else min(SLOT, ((X1 - X0) - GAP * (len(row) - 1)) // sum(slots))
            fixed = sum(s * slot for s in slots if s)
            free = (X1 - X0) - fixed - GAP * (len(row) - 1)
            x = X0
            for (title, names), s in zip(row, slots):
                w = s * slot if s else free // max(nchoice, 1)
                lines.append('frame x=%d y=%d w=%d h=%d title="%s"' % (x, y, w, row_h, title))
                if s:   # knobs, evenly spread
                    for i, n in enumerate(names):
                        cx = x + slot // 2 + i * slot
                        cy = y + TITLE + r + 5
                        lines.append('knob cx=%d cy=%d r=%d label="%s" key=%s' % (cx, cy, r, n.upper(), key(n)))
                        qlinks.append(key(n))
                else:   # a choice: one button per option, in as many rows as it needs
                    opts = by_name[names[0]]["options"]
                    nrows = 1 if len(opts) <= 4 else 2
                    per = -(-len(opts) // nrows)
                    sw = min(250, (w - 40 - 2 * (per - 1)) // per)
                    cy = y + TITLE + (row_h - TITLE) // 2 - (nrows - 1) * 23   # buttons are 44 px + 2 px apart
                    lines.append('enum_h cx=%d cy=%d sw=%d rows=%d label="" key=%s options="%s"'
                                 % (x + w // 2, cy, sw, nrows, key(names[0]), ",".join(opts)))
                    qlinks.append(key(names[0]))
                x += w + GAP
            y += row_h + GAP
        if y - GAP > 714:
            sys.exit("%s: page too tall (%d)" % (plug, y - GAP))
        lines.append('qlinks "%s" = %s' % (name.split()[1].upper(), ",".join(qlinks[:16])))

        d = os.path.join(out, plug)
        os.makedirs(d, exist_ok=True)
        json.dump({"name": name, "params": params}, open(os.path.join(d, "params.json"), "w"), indent=1)
        json.dump({"name": name, "vendor": vendor, "uid": uid, "version": 1000, "so": plug + ".so",
                   "params": "params.json", "layout": "layout.conf"}, open(os.path.join(d, "vst.json"), "w"), indent=1)
        open(os.path.join(d, "layout.conf"), "w").write("\n".join(lines) + "\n")
        print("%s: %d params, %d rows" % (plug, len(params), len(rows)))


if __name__ == "__main__":
    main(*sys.argv[1:])
