#!/usr/bin/env python3
"""Write the MPC touchscreen page sources (vst.json, params.json, layout.conf) for the Airwindows vocal set.

    pages.py <params dir> <out dir>

<params dir>/<Plugin>.raw.json is each plugin's own parameter list (tools/vst_test --params-json), so the page binds
to the plugin's own parameter order. Airwindows' parameters are all 0-1 knobs; each page is one row of big knobs
under a title saying what the plugin is. Text is 1.35x (a knob of radius r needs r+5 above its centre, r+72 below).
"""
import json
import os
import re
import sys

# plugin: page title (what it is)
PLUGINS = {
    "DeBess": "DE-ESSER",
    "VariMu": "VARI-MU TUBE COMPRESSOR",
    "ButterComp2": "SMOOTH COMPRESSOR",
    "Pressure6": "COMPRESSOR",
    "Air4": "AIR (HIGH END)",
    "Baxandall3": "BASS + TREBLE EQ",
    "Tube2": "TUBE SATURATION",
    "Doublelay": "DOUBLER",
    "Verbity2": "REVERB",
}
# Airwindows' short names spelled out for the knob labels
LABELS = {"Intensty": "Intensity", "Compres": "Compress", "Gnd": "Ground", "DarkF": "Dark Freq",
          "Feedbk": "Feedback", "RmSize": "Room Size", "Delay L": "Delay L", "Delay R": "Delay R"}
# switches (on above 0.5): parameter -> the toggle's label. DeBess' Sense plays only what it detects as esses.
SWITCHES = {("DeBess", "Sense"): "Listen"}

X0, X1, Y0 = 20, 1260, 96
TITLE = 50


def key(name):
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def main(pdir, out):
    here = os.path.dirname(os.path.abspath(__file__))
    for plug, title in PLUGINS.items():
        header = open(os.path.join(here, "airwindows", plug, plug + ".h")).read()
        uid = re.search(r"kUniqueId = '(\w{4})'", header).group(1)
        raw = json.load(open(os.path.join(pdir, plug + ".raw.json")))
        params, knobs, switches = [], [], []
        for p in raw:   # VST index order
            q = {"key": key(p["name"]), "name": LABELS.get(p["name"], p["name"])}
            sw = SWITCHES.get((plug, p["name"]))
            if sw:
                q.update({"name": sw, "options": ["Off", "On"]})
                switches.append(q)
            else:
                q.update({"min": 0, "max": 1, "default": round(p["default"], 4), "unit": p["unit"]})
                knobs.append(q)
            params.append(q)

        n = len(knobs) + len(switches)
        r = 64 if n <= 3 else 56 if n == 4 else 50
        slot = min(280, (X1 - X0) // n)                   # knobs grouped in the middle, not spread edge to edge
        x = X0 + ((X1 - X0) - n * slot) // 2
        h = TITLE + 30 + (r + 5) + (r + 72) + 30
        cy = Y0 + TITLE + 30 + r + 5
        lines = ["# %s page: generated by airwindows-mpc/pages.py" % plug, "[tab %s]" % plug.upper(),
                 'frame x=%d y=%d w=%d h=%d title="%s"' % (X0, Y0, X1 - X0, h, title)]
        for i, q in enumerate(knobs + switches):
            cx = x + slot // 2 + i * slot
            if "options" in q:
                lines.append('toggle cx=%d cy=%d label="%s" key=%s' % (cx, cy, q["name"].upper(), q["key"]))
            else:
                lines.append('knob cx=%d cy=%d r=%d label="%s" key=%s' % (cx, cy, r, q["name"].upper(), q["key"]))
        lines.append('qlinks "%s" = %s' % (plug.upper(), ",".join(q["key"] for q in params)))

        d = os.path.join(out, plug)
        os.makedirs(d, exist_ok=True)
        json.dump({"name": plug, "params": params}, open(os.path.join(d, "params.json"), "w"), indent=1)
        json.dump({"name": plug, "vendor": "airwindows", "uid": uid, "version": 1000, "so": "Airwindows" + plug + ".so",
                   "params": "params.json", "layout": "layout.conf"}, open(os.path.join(d, "vst.json"), "w"), indent=1)
        open(os.path.join(d, "layout.conf"), "w").write("\n".join(lines) + "\n")
        print("%s: %d params" % (plug, len(params)))


if __name__ == "__main__":
    main(*sys.argv[1:])
